import { CotMarketDefinition } from '../interfaces';

export const COT_DEFAULT_MARKET_CODE = '088691';

/**
 * A trader-facing subset of the ~360 contracts the CFTC publishes. Every entry
 * appears in the legacy release plus exactly one detail taxonomy: physical
 * commodities are disaggregated, financial futures use TFF.
 */
export const COT_MARKETS: CotMarketDefinition[] = [
  {
    code: '088691',
    label: 'Gold',
    group: 'Metals',
    exchange: 'COMEX',
    contractUnit: '100 troy ounces',
    symbol: 'XAUUSD',
    detail: 'disaggregated',
  },
  {
    code: '084691',
    label: 'Silver',
    group: 'Metals',
    exchange: 'COMEX',
    contractUnit: '5,000 troy ounces',
    symbol: 'XAGUSD',
    detail: 'disaggregated',
  },
  {
    code: '085692',
    label: 'Copper',
    group: 'Metals',
    exchange: 'COMEX',
    contractUnit: '25,000 pounds',
    symbol: 'XCUUSD',
    detail: 'disaggregated',
  },
  {
    code: '076651',
    label: 'Platinum',
    group: 'Metals',
    exchange: 'NYMEX',
    contractUnit: '50 troy ounces',
    symbol: 'XPTUSD',
    detail: 'disaggregated',
  },
  {
    code: '075651',
    label: 'Palladium',
    group: 'Metals',
    exchange: 'NYMEX',
    contractUnit: '100 troy ounces',
    symbol: 'XPDUSD',
    detail: 'disaggregated',
  },
  {
    code: '067651',
    label: 'Crude Oil (WTI)',
    group: 'Energy',
    exchange: 'NYMEX',
    contractUnit: '1,000 barrels',
    symbol: 'USOIL',
    detail: 'disaggregated',
  },
  {
    code: '023651',
    label: 'Natural Gas',
    group: 'Energy',
    exchange: 'NYMEX',
    contractUnit: "10,000 MMBtu",
    symbol: 'NGAS',
    detail: 'disaggregated',
  },
  {
    code: '098662',
    label: 'US Dollar Index',
    group: 'Currencies',
    exchange: 'ICE US',
    contractUnit: 'USD index × $1,000',
    symbol: 'DXY',
    detail: 'financial',
  },
  {
    code: '099741',
    label: 'Euro FX',
    group: 'Currencies',
    exchange: 'CME',
    contractUnit: 'EUR 125,000',
    symbol: 'EURUSD',
    detail: 'financial',
  },
  {
    code: '096742',
    label: 'British Pound',
    group: 'Currencies',
    exchange: 'CME',
    contractUnit: 'GBP 62,500',
    symbol: 'GBPUSD',
    detail: 'financial',
  },
  {
    code: '097741',
    label: 'Japanese Yen',
    group: 'Currencies',
    exchange: 'CME',
    contractUnit: 'JPY 12,500,000',
    symbol: 'USDJPY',
    detail: 'financial',
  },
  {
    code: '092741',
    label: 'Swiss Franc',
    group: 'Currencies',
    exchange: 'CME',
    contractUnit: 'CHF 125,000',
    symbol: 'USDCHF',
    detail: 'financial',
  },
  {
    code: '232741',
    label: 'Australian Dollar',
    group: 'Currencies',
    exchange: 'CME',
    contractUnit: 'AUD 100,000',
    symbol: 'AUDUSD',
    detail: 'financial',
  },
  {
    code: '090741',
    label: 'Canadian Dollar',
    group: 'Currencies',
    exchange: 'CME',
    contractUnit: 'CAD 100,000',
    symbol: 'USDCAD',
    detail: 'financial',
  },
  {
    code: '112741',
    label: 'New Zealand Dollar',
    group: 'Currencies',
    exchange: 'CME',
    contractUnit: 'NZD 100,000',
    symbol: 'NZDUSD',
    detail: 'financial',
  },
  {
    code: '13874A',
    label: 'E-mini S&P 500',
    group: 'Indices',
    exchange: 'CME',
    contractUnit: '$50 × S&P 500 index',
    symbol: 'US500',
    detail: 'financial',
  },
  {
    code: '209742',
    label: 'E-mini Nasdaq 100',
    group: 'Indices',
    exchange: 'CME',
    contractUnit: '$20 × Nasdaq 100 index',
    symbol: 'US100',
    detail: 'financial',
  },
  {
    code: '124603',
    label: 'E-mini Dow (DJIA)',
    group: 'Indices',
    exchange: 'CBOT',
    contractUnit: '$5 × DJIA index',
    symbol: 'US30',
    detail: 'financial',
  },
  {
    code: '133741',
    label: 'Bitcoin',
    group: 'Crypto',
    exchange: 'CME',
    contractUnit: '5 bitcoin',
    symbol: 'BTCUSD',
    detail: 'financial',
  },
  {
    code: '146021',
    label: 'Ether',
    group: 'Crypto',
    exchange: 'CME',
    contractUnit: '50 ether',
    symbol: 'ETHUSD',
    detail: 'financial',
  },
  {
    code: '043602',
    label: 'UST 10Y Note',
    group: 'Rates',
    exchange: 'CBOT',
    contractUnit: '$100,000 face value',
    symbol: null,
    detail: 'financial',
  },
  {
    code: '020604',
    label: 'Ultra UST Bond',
    group: 'Rates',
    exchange: 'CBOT',
    contractUnit: '$100,000 face value',
    symbol: null,
    detail: 'financial',
  },
];

export const COT_MARKETS_BY_CODE = new Map(COT_MARKETS.map((market) => [market.code, market]));
